### ISSUE TITLE
Simplify Pingdom request detection

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-pingdom-status#17]
**Is your feature request related to a problem? Please describe.**
The current heuristics to detect a Pingdom status check request are to complicated and restrictive. Pingdom request detection is e.g. based on the absence of query parameters. It's therefore not possible to use real world action invocations for status checks.

**Describe the solution you'd like**
Simplify the heuristics by just using the `User-Agent` header to determine whether it is a Pingdom status check request or not.

**Comment by tripodsan** [comment]
I would even simplify it more and just use a dedicated url, eg: `/_status_check/pingdom.xml`

**Comment by stefan-guggisberg** [comment]
> I would even simplify it more and just use a dedicated url, eg: /_status_check/pingdom.xml

I agree, less magic. @trieloff WDYT?
